M48
; DRILL file {KiCad 9.0.7} date 2026-06-23T14:22:29+0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-23T14:22:29+05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.300
%
G90
G05
T1
X12.0Y-21.5
X22.5Y-22.5
X32.0Y-14.5
X37.0Y-28.0
T2
X30.5Y-11.0
X35.58Y-11.0
M30
